language: node_js
node_js:
- node
branches:
  only: master
before_script:
- git config --global user.email "email@denysdovhan.com"
- git config --global user.name "Denys Dovhan"
- git remote rm origin
- git remote add origin https://denysdovhan:${GH_TOKEN}@github.com/LambdaBooks/thelittlebookofruby.git
script:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run deploy || npm run build'
env:
  global:
    secure: fmpMp0KpkIj3HhnrkAwrbjJhNkWxBXsSVKa6DMM4E9LDsymHdpo967jeZ/3iA4uKKY2ZTWEPyvuLxXTLB0xNOfPKraDJb6RZhpsgvk60+XS869PAfC6z8NpQ5gBUxX+pALZFW1aljRFGpVfPCYBa0epV0sni9nlb1Viln4CHwEwBVJ+JlVh6sezOwqe3aDsVR8RvP+izvocH9lH5poCcxflG3SNLR70NnJMW8X3ToJL3SWdqemjMi5FdbFH20209axd3SlGLoCSf7zCfnffXAqkpLxLPNit13Nt8y2NdZlZhcEuBuA8xQmpRWBcDj+qwt5ccyb5EzW+w/abyZxM9724/9e8GHidcuGKuMpSvS40EpQUNjEQiKvdy1vMoOtwKaGdciV9hAbEItAW7+tB8XWbQhqWGs7xX5SMdQ8gqgxbLTZb9KwHZBRM54mIsgAcnazXq/9Ju8TrGVaOFei+iMll2LsrMqh1cZ9g7TMZiF/tegLnnSMMaN1sR+iDmc71JVP/7FJiMtYPvAddAvt3thRchhGDIF92rlod8WiUiVgt4zNQqEgrkLOCMD2Nx8WDoKGUEn4vHQ/muKcqZ6b+Q+DCUVAaQwE5wmNM5DTiLk9SUtcv6/cw6qdfoEflmuVsJHER3vn3L+NmU0qjOPajthDNIaUjqRRj0jyr1sR3pBYg=
notifications:
  slack:
    secure: Kjvrde5OnfcsJM5DUDgfVWgfhJZM8r6EraYfMAZL34cWUEzamKsq12qqZPCVbF1k/5/TxJtScfPRsNmA3j5N857g7tNMUuwRQLRA5604NqiHSP4nT7dnOPytmUCjf72JGEjDo7jY9yPZQOSTUl3Fk7mRi6YYtfGF53ovrF/fLqqvM9U7niKFIMHLQbnemnjAkK/emkaruIz6keD0Vl/z1iKtis8+2BXNGND1Dug4jLV7P1pW71DhQKPxv1MA3UGgAIgTORDMIohxT64GRIt8cSXSuZf+PfFqTnbWg9yswVJaLWwZ1IT2qeXyCcs3QHZco/RoeyvAxSwbfLm+vT2y2byh7CDMVybjpxgV+snSmNxMHSLTVO1VVM7HQjXvoiiBqbZonw4K0NLXjgxTXHlNMbMHGuVxHb0WbjqatcgWk2NemNzLCkgDEAfgG680PXRTLQ3H3XXX1+fbUNI9jb920JIppU6WuXH3snJqyV/OMr7rKi6Kzy/JFkALnm0dfXPBYZfElC67toRtn1wM8WoBw8WkfGo355AQiYvx4Hq8rq/vvMu6NPNvzFgtKeymMeHULrcm1frwmI7XCz8dZR1W0rgKtdOBqvi/JVYQrdA1uJU09X29U3E4h2E9wPyFolNQHT5DbdFgU5iFjfPuyjT/jcTHgIzZSVCzREvZVjImic8=
